### ISSUE TITLE
slackinviter -h error

### ISSUE THREAD

**Issue by vijai1996** [flexd/slackinviter#17]
Hello,
I try to run the app using `slackinviter -h` and I get 

> 2017/04/20 20:47:40 required key SLACKINVITER_PORT missing value

Could you please let me know how to configure the app and run it?

**Comment by jamy015** [comment]
As a workaround to get you up and running, I think you can set the environment variables `SLACKINVITER_SLACKTOKEN`, `SLACKINVITER_CAPTCHASITEKEY` and `SLACKINVITER_CAPTCHASECRET`, and then just run `slackinviter`

**Comment by vijai1996** [comment]
I'm sorry but where could I set the environment variables and syntax? Thanks

**Comment by jamy015** [comment]
Check the section for your OS and shell on [this Wikipedia page](https://en.wikipedia.org/wiki/Environment_variable#Assignment).

**Comment by vijai1996** [comment]
Ah! its the user shell vars! I thought there could be something related to GO. I'd try now. thanks
Edit: Added the vars to my bash_profile still i get the same info when I run slackinviter

**Comment by jamy015** [comment]
Are you using the `export` keyword as described in that article?

> In Unix shells, variables may be assigned without the `export` keyword. Variables defined in this way are displayed by the `set` command, but are not true environment variables, as they are stored only by the shell and not recognized by the kernel. The `printenv` command will not display them, and child processes do not inherit them.

**Comment by vijai1996** [comment]
I solved the issue by adding the port the server has to listen to using `SLACKINVITER_PORT` variable as the binary reported and its up now. But, its listening on all domains/available IP. Is it possible to only listen for a certain domain/port?

**Comment by flexd** [comment]
@vijai1996 Currently it is not, but we can make that change easily enough. If anyone has the time, feel free to do so. I will try to do it this this week. :)
