### ISSUE TITLE
Does this have Recaptha

### ISSUE THREAD

**Issue by GiacomoLaw** [flexd/slackinviter#7]
Told it did, but I can't find it on my sign up form.

**Comment by GiacomoLaw** [comment]
Sorry, my problem.

**Comment by flexd** [comment]
It does! Let me know if you have any other questions :-)

**Comment by GiacomoLaw** [comment]
@flexd I realised, sorry!

**Comment by flexd** [comment]
No problem.. It's not very well documented :)
