### ISSUE TITLE
Images shown strangely

### ISSUE THREAD

**Issue by GiacomoLaw** [flexd/slackinviter#8]
http://redwings-va.herokuapp.com

![img_6929](https://cloud.githubusercontent.com/assets/9038673/19564621/17ae6f2e-96dc-11e6-8730-75f9dd8cd314.PNG)

Images are shown weirdly...

**Comment by freeformz** [comment]
Define "strangely" and "weirdly". AFAICT some of the strangeness is due to the red logo not having a transparent background (it has a roughly white border). But I'm not sure that is what you are talking about.

**Comment by GiacomoLaw** [comment]
The images appear to big. 😄

**Comment by flexd** [comment]
I'm not sure if this is what you were talking about, but I just made a tiny CSS change that moves the Slack logo 0.3em more to the right. Does it look better now?

If this wasn't it, I can't see what you are talking about.

**Comment by GiacomoLaw** [comment]
https://gyazo.com/223d376521d7d0e4be5a2781a5b78c6a

As you can see, the images overlap ^^^ 😄

**Comment by freeformz** [comment]
Oh the `+`. Lol yeah, there should probably be more spacing around it. TBH I didn't even see the plus.

**Comment by flexd** [comment]
That's where I added some spacing.. and it was also the first time I noticed there was a plus sign there :)

**Comment by flexd** [comment]
I should make the spacing there relative (in em) instead of pixels. That way it should work for all size logos.

**Comment by GiacomoLaw** [comment]
https://github.com/flexd/slackinviter/pull/10

Does that work? Not sure how to test it. 😄 @flexd

**Comment by flexd** [comment]
@GiacomoLaw It should be fixed in the latest master. Have you tried that? If not I can make additional changes. Adding spaces around the "+" is not the best way of solving this :-)

**Comment by GiacomoLaw** [comment]
Thank you! Any way I can update my app without having to delete and reinstall? 😄

**Comment by flexd** [comment]
You should be able to just run 'git pull' to get the latest updates.

**Comment by GiacomoLaw** [comment]
@flexd Can I find this here or on Heroku?

**Comment by freeformz** [comment]
@GiacomoLaw You have 3 options AFAICT:

1) Fork this repo to your own account and link it to the app then you can deploy from the web ui. But this (a) creates some garbage in your account and (b) you will have to keep the fork updated manually.

2)  Install the Heroku CLI (unless you already have it), checkout this repo locally, use the heroku cli to [setup the git remote](https://devcenter.heroku.com/articles/git) and then `git push heroku master` to the app.

3) If you can make a copy of the env vars, then you could destroy and re-create the app from the button though using the same name. That's kind of a pain though, so unless you are really against using some CLI commands I would suggest (2).

We (Heroku) do have a user story to make a button to make this easier (updating button apps deployed from public 3rd party repositories). It's not prioritized ATM though.

**Comment by GiacomoLaw** [comment]
@freeformz Thank you very much!
