### ISSUE TITLE
TODO: Document the project

### ISSUE THREAD

**Issue by flexd** [flexd/slackinviter#9]
This is just running flawlessly for us, so we haven't really documented anything. I should do that :)

**Comment by ghost** [comment]
You made me thinking of switching from rocket.chat to slack because of this lightweight public registration server , nice job, if you want open some issues/prosopal  with the things you want this project to have and I will help as much as I can!

**Comment by flexd** [comment]
Thanks for offering your help! We do not have any plans for adding any features to the project at this time, but I will make issues/proposals in the future if we do.

**Comment by dmitshur** [comment]
I'll link to this blog post, since it serves as documentation of sorts, or at least it's relevant.

https://cognitive.io/post/rewriting-the-gophers-invite-form-in-go/
